### ISSUE TITLE
Missing queryString 

### ISSUE THREAD

**Issue by mqliutie** [jeromeetienne/jquery-qrcode#114]
$('#qrCode').qrcode({ width: 80, height: 80, text: "http://xxx.xx.com?t=12312312" });

In some browser the `t=12312312` will be gone. 

Anyone can help?

**Comment by incitedigital** [comment]
Hello, I created variables for each of my parameters and then concatenated them together.  It works for me.  Here is an example.

var customer = $('#customer').val();
var location = $('#location').val();
var site = $('#site').val();
var menuID= $("#menuID").val();
var emails = $('#emails').val();

$('#qrcode').qrcode({width: 256,height: 256,text: 'https://xxx.xxx.xxx/?customer='+customer+'&location='+location+'&menuID='+menuID+'&site='+site+'&emails='+emails});

**Comment by mqliutie** [comment]
Fortunately, the QR code needs to be cut off.
